common/urls.py
from django.urls import path

from common.views import main_view

urlpatterns = [
    path("", main_view, name="main"),
]

dataminingtasks/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = (
        [
            path("", include(("common.urls", "common"), namespace="common")),
            path(
                "ad_statistics/itpedia",
                include(
                    ("webcrawlerbloggersad.urls", "webcrawlerbloggersad"),
                    namespace="webcrawlerbloggersad"
                )
            ),
            path(
                "page_rank",
                include(
                    ("pagerank.urls", "pagerank"),
                    namespace="pagerank"
                ),
            ),
            path('admin/', admin.site.urls),
        ]
        + static(settings.STATIC_URL)
)

pagerank/urls.py
from django.urls import re_path

from pagerank.views import main_view

urlpatterns = [
    re_path(r"/?", main_view, name="main"),
]

webcrawlerbloggersad/urls.py
from django.urls import path

from webcrawlerbloggersad.views import statistics_view

urlpatterns = [
    path("", statistics_view, name="main"),
]

common/models.py
from django.db import models

# Create your models here.

pagerank/models.py
from django.db import models


# Create your models here.

class Site(models.Model):
    link = models.URLField()
    rank = models.FloatField(default=1.0)
    group = models.ForeignKey("Group", on_delete=models.CASCADE,
                              related_name="sites")


class Group(models.Model):
    root = models.ForeignKey(
        Site,
        related_name="sites",
        on_delete=models.CASCADE, null=True, blank=True
    )
    created_at = models.DateTimeField(auto_created=True, auto_now=True)

webcrawlerbloggersad/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField


# Create your models here.

class Video(models.Model):
    title = models.CharField(max_length=256)
    description = models.TextField()
    date = models.DateTimeField()
    tags = ArrayField(models.CharField(max_length=256))
    like_count = models.BigIntegerField()
    view_count = models.BigIntegerField()
    comment_count = models.BigIntegerField()

    class Meta:
        db_table = "videos"


class Link(models.Model):
    link = models.URLField()
    video = models.ForeignKey(Video, on_delete=models.PROTECT)

    class Meta:
        db_table = "links"

pagerank/forms.py
from django.forms import forms, fields

from pagerank.services.sites_parsing import is_valid


class BootstrapFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = field.widget.attrs.get("class", "")
            field.widget.attrs["class"] += " form-control"


class SiteForm(BootstrapFormMixin, forms.Form):
    link = fields.URLField()

    def clean(self):
        cleaned_data = super(SiteForm, self).clean()
        if not is_valid(cleaned_data["link"]):
            self.add_error(None, "Link is not valid")
        return cleaned_data

common/views.py
from django.shortcuts import render


def main_view(request):
    return render(request, "common/main.html")

pagerank/views.py
from django.shortcuts import render

from pagerank.forms import SiteForm
from pagerank.tasks import calculate_page_rank


def main_view(request):
    context = {"form": SiteForm(), "alert": False}
    if request.method == "POST":
        form = SiteForm(request.POST)
        context["form"] = form
        if form.is_valid():
            link = form.cleaned_data["link"]
            print("everything is cool")
            calculate_page_rank.delay(link)
            print("everything is very cool")
        context["alert"] = "Wait for it. You can return to site in a few hours."
    return render(request, "pagerank/main.html", context)

webcrawlerbloggersad/views.py
from django.shortcuts import render

# Create your views here.


def statistics_view(request):
    context = {"iframes_urls": [
        "https://datalens.yandex/v1xkgtndg7x2n",
        "https://datalens.yandex/flh204r0rs927"
    ]}
    return render(request, "webcrawlerbloggersad/main.html", context)

common/templates/common/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Главная{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'common/css/bootstrap.min.css' %}">
    <script
            src="{% static 'common/js/bootstrap.bundle.min.js' %}"></script>

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'common:main' %}">
            Главная
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent1">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link"
                       href="{% url 'webcrawlerbloggersad:main' %}">Статистика
                        по рекламе на канале Itпедия</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"
                       href="{% url 'pagerank:main' %}">Page
                        Rank</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div id="main" class="container">
    <div>
        {% block content %}
        {% endblock %}
    </div>
</div>

</body>
</html>

common/templates/common/main.html
{% extends 'common/base.html' %}
{% block content %}
    <p>Здесь я буду выкладывать свои работы в рамках курса DataMining</p>
{% endblock %}

pagerank/templates/pagerank/main.html
{% extends 'common/base.html' %}
{% block content %}
    <p>
        This is PageRank algorithm!
    </p>
    <form action="{% url 'pagerank:main' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary">leave a request for pagerank calculation</button>
    </form>
    {% if alert != 'False' %}
    <div class="alert alert-primary" role="alert">
        {{ alert }}
    </div>
    {% endif %}




{% endblock %}

webcrawlerbloggersad/templates/webcrawlerbloggersad/main.html
{% extends 'common/base.html' %}
{% block content %}
    <style>
        body {
            margin: 0;            /* Reset default margin */
        }
        iframe {
            display: block;       /* iframes are inline by default */
            background: #000;
            border: none;         /* Reset default border */
            height: 100vh;        /* Viewport-relative units */
            width: 100%;
        }
    </style>
    {% for link in iframes_urls %}
        <iframe height="100%" width="100%"
                src="{{ link }}?_embedded=1&_theme=dark"></iframe>
        <br>
    {% endfor %}
{% endblock %}